import './globals.css'
import localFont from "next/font/local"
import {NextUIProvider} from "@nextui-org/system";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
        <main className="min-h-screen bg-background flex flex-col items-center">
          {children}
        </main>
        </NextUIProvider>
      </body>
    </html>
  )
}
